Post Detail 구현
TIL-Log-lab/Tilog-web-node-v2 pull request #54
Opened 2022-05-16 12:24 UTC by MINJE-98

# 구현 개요

Post Detail을 SEO를 고려하여 컴포넌트를 구현합니다.
1. 처음 내려받는 Post Detail의 정보는 Server에서 전달받은 데이터입니다.
2. 추가적인 데이터 요청 및 호출은 CSR으로 동작합니다.

## 작업 사항

- ServerSide에서 Post Detail Fetching
- date-fns 설치 및 포스트 날짜에 사용하기 위해 레핑
- like custom hooks 작성
- Post Detail내용을 Fetching된 데이터로 모두 변경

## 이슈 트래커 번호

resolve #53  

# Refactor

- 테크 아이콘을 입력, 출력 모두 Upper Case로 변경하였습니다.
- accessToken refresh방식 변경

2022-05-19 14:41 UTC, argon1025 requested changes
확인한번 해줘용~!

2022-05-19 16:43 UTC, MINJE-98 commented on src/pages/post/[postId].tsx
> +    };
서버 사이드에서 비밀글과 일반글을 검증하고 props로 반환하면 클라이언트단에서 postDetail에 해당하는 데이터에 대해서만 검증하여 컴포넌트를 그리도록 설계하였습니다.

만약 서버사이드에서 일반글만 판별하게 되면 클라이언트사이드에서 또다시 인증이 포함된 api call을 해야하는 상황입니다.

2022-05-22 05:40 UTC, argon1025 requested changes
확인해주세요!

2022-05-22 05:40 UTC, argon1025 commented on src/pages/post/[postId].tsx
> +
포스트 세부 정보를 로드하는 함수에서
인증을 함께 처리하는 건 좋지 않은 것 같습니다
하나의 역할만 수행하도록 분리하는게 어떨까요?

2022-05-30 07:27 UTC, MINJE-98 commented
로그인 스팩 변경으로 PR을 닫고 새로운 브랜치에서 작업합니다.

2022-05-30 07:27 UTC, closed without merging