client, server 측 인증 로직을 분리
TIL-Log-lab/Tilog-web-node-v2 pull request #67
Opened 2022-06-03 13:23 UTC by MINJE-98

# 구현 개요

client, server 측 인증 로직을 분리

## 작업 사항
### redux
- accessToken추가
- userInfo 로그인 상태 추가

### ServerSideProps(Server)
ServerSideProps 인증 레퍼 작성

- token만료 여부 반환 함수 작성
- 서버측에서 axios 호출을 하는 함수 작성
- 요구사항 변경으로 로그인 로그아웃 컴포넌트 수정

## 이슈 트래커 번호

resolve #62 

# Refactor

### redux
- slice를 slices폴더로 이동

### axios(Client)
글로벌 axios 인스턴스 생성
   관련된 로직 수정

2022-06-03 14:24 UTC, argon1025 commented on src/hooks/redux/slices/accessToken.ts
> +};
데이터가 비었을 경우, 스트링이 있을 경우를 엄격하게 구분하는게 어떨까요

2022-06-03 14:27 UTC, argon1025 commented on lib/open-api/core.ts
> +);
async function으로 가능하다면 통일하는게 어떨까요

2022-06-03 17:13 UTC, argon1025 requested changes
확인해 주세요!

2022-06-03 17:13 UTC, argon1025 commented on src/components/organisms/Header.tsx
> +  const name = useSelector(usernameSelector);
요 부분에서 리턴타입이 확실하지 않은 것 같은데 제네릭을 useSelector에서 사용할 수 있을까요?

2022-06-03 18:31 UTC, MINJE-98 commented on src/components/organisms/Header.tsx
> +  const name = useSelector(usernameSelector);
제네릭을 사용하지 않아도 usernameSelector를 사용하여 확실한 타입을 반환합니다.

```typescript
// State
type State = {
    TILog_Info: UserInfoSliceState;
}

// UserInfoSlicecState
interface UserInfoSliceState {
  name: GetMeResponseDto["name"];
  avatar: GetMeResponseDto["avatar"];
  createdAt: GetMeResponseDto["createdAt"];
  language: CountryUnionType;
  isLogin: boolean;
  settings: GetMeResponseDto["settings"];
}

const usernameSelector = createSelector(
  (state: State) => state[userInfoSlice.name].name,
  (name) => name
);


// useSelector 제네릭
useSelector<{TILog_Info: UserInfoSliceState}, string>
```
createSelector의 첫번째 콜백의 인자값을 State 타입으로 지정하면 제네릭의 첫번째 인자 타입이 State타입으로 지정이됩니다.
두번째 콜백의 반환값은 제네릭의 두번째 인자 타입으로 지정이 됩니다.

2022-06-05 07:39 UTC, argon1025 submitted a review, later dismissed

2022-06-07 04:13 UTC, closed without merging