silent refreshing accessToken
TIL-Log-lab/Tilog-web-node-v2 pull request #72
Opened 2022-06-07 06:08 UTC by MINJE-98

# 구현 개요
accessToken이 만료 되거나, 없는 경우 조용히 토큰을 발급합니다.

# 작업 사항
client, server 마다 accessToken 토큰 발급 로직
accessToken 토큰 발급에 필요한 유틸리티 작성
요구사항 변경으로 로그인 로그아웃 컴포넌트 수정

## redux
userInfo 로그인 상태 추가

# 이슈 트래커 번호
resolve #62

2022-06-12 13:59 UTC, argon1025 commented on lib/auth/clientSideAuthentication.ts
> +  // NOTE: 비회원
요 코드는 한번에 의도 파악이 가능하기 때문에 주석은 제거합시다

2022-06-12 14:02 UTC, argon1025 commented on lib/auth/clientSideAuthentication.ts
> +      await TilogApiForAuth.usersAuthControllerGetAccessTokenUsingRefreshToken();
해당 OpenAPI SDK 메서드같은 경우
백엔드에서 open-api generator를 통해서 자동으로 메서드 명이 정의 됩니다.
백엔드 작업중에 해당 메서드 이름이 변경될 경우 프론트에서 대응하기 힘들 수 있기 때문에
추가적으로 어뎁팅해서 사용하시는것을 권장합니다.

2022-06-12 14:05 UTC, argon1025 commented on lib/auth/serverSideAuthentication.ts
> +    // NOTE: accessToken이 사용하능할 때
오타가 있어요!

2022-06-12 14:06 UTC, argon1025 commented on lib/auth/serverSideAuthentication.ts
> +    const { isLogin } = store.getState().TILog_Info;
headers의 변수 수명 주기가 많이 길어 보여요
함수 범위 전체에서 사용할 경우 상수 HEADERS로 하거나, 사용하는 부분에서 선언하는것이 필요해 보입니다

2022-06-12 14:12 UTC, argon1025 requested changes
요 부분에 대해서 어떻게 생각하시나요!

2022-06-13 05:15 UTC, MINJE-98 commented on lib/auth/serverSideAuthentication.ts
> +    const { isLogin } = store.getState().TILog_Info;
현재 header는 clientHeaders에서만 사용하고 있기 때문에 변수 수명 주기가 길지 않습니다. 
선언부와 변수를 사용하고 있는 부분으로 이동하겠습니다~

2022-06-13 16:31 UTC, argon1025 approved these changes
좋습니다~

2022-06-14 14:51 UTC, merged