ReactQuery Auth Wrapping Custom Hook
TIL-Log-lab/Tilog-web-node-v2 pull request #75
Opened 2022-06-13 07:23 UTC by MINJE-98

# 구현 개요

ReactQuery Auth Wrapping Custom Hook

## 작업 사항

1. query 인증 레퍼
2. muetaion 인증 레퍼

## 이슈 트래커 번호

resolve #74

2022-06-13 16:33 UTC, argon1025 commented on src/hooks/react-query/auth-wrapper/useAuthMutation.ts
> +    async (data: T) => await clientSideAuthentication(() => callback(data))
Async fuc은 Primise를 리턴하기 때문에 await를 사용할 필요가 없는 것 같습니다.
코드스멜에도 해당 내용이 있으니 수정 부탁 드려요!

2022-06-13 16:33 UTC, argon1025 commented on src/hooks/react-query/auth-wrapper/useAuthMutation.ts
> +//TODO: 메서드명 변경해야함.
TODO는 해결합시다~

2022-06-13 16:34 UTC, argon1025 commented on src/hooks/react-query/auth-wrapper/useAuthQuery.ts
> +    async () => await clientSideAuthentication(callback),
이 부분도 마찬가지 입니다.

2022-06-13 16:34 UTC, argon1025 requested changes
확인 부탁드려요!

2022-06-14 03:24 UTC, MINJE-98 commented
- TODO 해결하였습니다.
- Promise callback 자체가 Promise이기 때문에 Promise로 두번 감싸기 때문에 async를 제거하였습니다.

2022-06-15 12:59 UTC, argon1025 approved these changes
좋아용~

2022-06-15 13:00 UTC, merged