Post Detail 구현
TIL-Log-lab/Tilog-web-node-v2 pull request #77
Opened 2022-06-15 15:32 UTC by MINJE-98

# 구현 개요

Post Detail 구현

## 작업 사항

1. PostDetail 관련 컴포넌트 구현
2. LikeButton 관련 컴포넌트 구현
 a. LikeQuery 구현
 b. LikeMutation 구현
 c. 상태별 컴포넌트 구현

## 이슈 트래커 번호

resolve #53 

# 기타 변경 사항

1. axiosInstance 변경 후 반영안된 코드 수정
4. techIcon TypeScript 키값 수정
5. serverSideAuthentication에 try catch 추가,  인증시 refreshToken 주입 코드 수정

2022-06-17 03:22 UTC, argon1025 requested changes
확인 해 주세요!

2022-06-17 03:22 UTC, argon1025 commented on lib/open-api/adapter/postLike.ts
> +  postId: TILog.UnsetLikedRequestDto["postId"],
지금 봤는데 DTO Interface 객체도 OpenAPI generator가
백엔드 Interface 명을 기반으로 생성합니다
이것도 메서드 래핑하는것 처럼 다시 내보내거나 프론트 고유의 인터페이스를 만들고 implements 하시는게 좋을것 같습니다

2022-06-17 03:33 UTC, MINJE-98 commented on lib/open-api/adapter/postLike.ts
> +  postId: TILog.UnsetLikedRequestDto["postId"],
좋은 방법인 것 같습니다. 
새롭게 이슈를 등록하여 작업하도록 하겠습니다😄

2022-06-18 02:37 UTC, argon1025 approved these changes

2022-06-18 02:52 UTC, merged